baseURL = "https://contributor-covenant.org"
canonifyURLs = false
languageCode = "en-us"
title = "Contributor Covenant"
disableKinds = ["RSS"]

DefaultContentLanguage = "en"
hasCJKLanguage = true
EnableMissingTranslationPlaceholders = true

uglyURLs = false

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[mediaTypes."text/plain"]
suffixes = ["txt"]

[mediaTypes."text/asciidoc"]
suffixes = ["adoc"]

[outputFormats]
[outputFormats.Markdown]
mediaType = "text/markdown"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputFormats.PlainText]
mediaType = "text/plain"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputFormats.AsciiDoc]
mediaType = "text/asciidoc"
isPlainText = true
baseName = "CODE_OF_CONDUCT"

[outputs]
home = ["html"]
page = ["html", "markdown", "plaintext", "asciidoc"]

# Add all translated languages here.
[languages]
[languages.ar]
languageName = "العربية"
languageCode = "ar"
[languages.ar.params]
	writingDirection = "rtl"

[languages.bn]
languageName = "Bengali"
languageCode = "bn"

[languages.bs]
languageName = "Bosnian"
languageCode = "bs"

[languages.ca]
languageName = "Català"
languageCode = "ca"

[languages.da]
languageName = "Dansk"
languageCode = "da"

[languages.de]
languageName = "Deutsch"
languageCode = "de"

[languages.en]
languageName = "English"
languageCode = "en"
weight = 1

[languages.el]
languageName = "ελληνικά"
languageCode = "el"

[languages.es]
languageName = "Español"
languageCode = "es"

[languages.fr]
languageName = "Français"
languageCode = "fr"

[languages.gu]
languageName = "ગુજરાતી"
languageCode = "gu"

[languages.hi]
languageName = "हिंदी"
languageCode = "hi"

[languages.hu]
languageName = "Magyar"
languageCode = "hu"

[languages.id]
languageName = "Indonesian"
languageCode = "id"

[languages.is]
languageName = "Íslenska"
languageCode = "is"

[languages.it]
languageName = "Italiano"
languageCode = "it"

[languages.iw]
languageName = "עברית"
languageCode = "iw"
[languages.iw.params]
	writingDirection = "rtl"

[languages.ja]
languageName = "日本語"
languageCode = "ja"

[languages.mr]
languageName = "मराठी"
languageCode = "mr"

[languages.kn]
languageName = "ಕನ್ನಡ"
languageCode = "kn"

[languages.ko]
languageName = "한국어"
languageCode = "ko"

[languages.mk]
languageName = "Македонски"
languageCode = "mk"

[languages.nl]
languageName = "Nederlands"
languageCode = "nl"

[languages.pl]
languageName = "Polski"
languageCode = "pl"

[languages.pt]
languageName = "Português"
languageCode = "pt"

[languages.pt-br]
languageName = "Português do Brasil"
languageCode = "pt-br"

[languages.ro]
languageName = "Română"
languageCode = "ro"

[languages.ru]
languageName = "Русский"
languageCode = "ru"

[languages.sl]
languageName = "Slovenščina"
languageCode = "sl"

[languages.sv]
languageName = "Svenska"
languageCode = "sv"

[languages.tr]
languageName = "Türkçe"
languageCode = "tr"

[languages.zh-tw]
languageName = "繁體中文"
languageCode = "zh-tw"

[languages.uk]
languageName = "Українська"
languageCode = "uk"

[languages.zh-cn]
languageName = "简体中文"
languageCode = "zh-cn"

[languages.fa-IR]
languageName = "فارسی"
languageCode = "fa-IR"
[languages.fa-IR.params]
	writingDirection = "rtl"
