name: 💡 General Feature Request
description: Submit a feature request.
title: "[FEATURE]: Description of feature here"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request. Please search the issue tracker to see if there is an existing issue for the feature you are requesting before submitting.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear description of the feature you would like to see added.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Share how you feel this would benefit the project.
    validations: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here that you feel would be helpful.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree that you have searched to see if the issue hasn't been documented all ready, and that I agree to follow the Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
